language: php
php:
    - 5.5
    - 5.4
    - 5.3

branches:
  only:
      - master

services:

before_script:
    - sudo apt-get update
    - sudo apt-get install -y --force-yes proftpd-basic libssh2-1-dev
    - printf "\n" | pecl install channel://pecl.php.net/ssh2-0.12
    - sudo bash -c 'cat /etc/proftpd/proftpd.conf | sed "s/^.*DefaultRoot.*$/DefaultRoot ~/" | sed "s/^.*ListOptions.*$/ListOptions \"-la\"/" > /etc/proftpd/proftpd.conf.tmp'
    - sudo mv /etc/proftpd/proftpd.conf.tmp /etc/proftpd/proftpd.conf
    - sudo /etc/init.d/proftpd restart
    - sudo useradd -m -p co.yjyxRTlonU testuser
    - mkdir ssh
    - ssh-keygen -N testkeypass -f ssh/testkey
    - openssl rsa -passin pass:testkeypass -in ssh/testkey -out ssh/testkey
    - sudo mkdir /home/testuser/.ssh
    - sudo cp ssh/testkey.pub /home/testuser/.ssh/authorized_keys
    - sudo chown -R testuser:testuser /home/testuser/.ssh
    - fingerprint=$(ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub | awk '{print $2}' | sed 's/://g')
    - cat Tests/PHPUnit.xml | sed "s/fingerprint/$fingerprint/" > Tests/PHPUnit.xml.tmp
    - mv Tests/PHPUnit.xml.tmp Tests/PHPUnit.xml

script: phpunit --configuration Tests/PHPUnit.xml Tests/

